spring:
  profiles:
    default: stdio
  threads:
    virtual:
      enabled: true
  ai:
    mcp:
      server:
        name: discogs-mcp-server
        version: 0.2.0

discogs:
  api:
    token: ${DISCOGS_TOKEN:}
    baseurl: ${DISCOGS_BASEURL:https://api.discogs.com}
    timeout: ${DISCOGS_TIMEOUT:5000}
    pagesize: ${DISCOGS_PAGESIZE:30}