spring:
  application:
    name: discogs-mcp-server
    version: 0.0.1-SNAPSHOT

discogs:
  api:
    token: ${DISCOGS_TOKEN}
    baseurl: ${DISCOGS_BASEURL:https://api.discogs.com}
    timeout: ${DISCOGS_TIMEOUT:3000}
    pagesize: ${DISCOGS_PAGESIZE:30}